import { Prisma } from '@prisma/client';

export const categories = [
  {
    name: 'Electronics',
    slug: 'electronics',
    description:
      'Discover a wide range of cutting-edge electronics, from smartphones and laptops to home entertainment systems.',
    metadata: {
      featured: 'true',
      display_order: '1',
    },
    seoSlug: 'buy-electronics-online',
    seoTitle: 'Shop Electronics & Gadgets | Best Prices',
    seoDescription:
      'Explore our collection of electronics. Find laptops, TVs, cameras, and more with the best deals and fast shipping.',
    backgroundImage: 'https://example.com/images/electronics-bg.jpg',
    backgroundImageAlt: 'A collection of electronic gadgets',
    isActive: true,
  },
  {
    name: 'Laptops & Computers',
    slug: 'laptops-computers',
    description:
      'High-performance laptops, desktops, and computer accessories for work, gaming, and creative projects.',
    metadata: {
      color: 'blue',
    },
    seoSlug: 'laptops-and-computers',
    seoTitle: 'Laptops & PCs for Sale | Dell, HP, Apple',
    seoDescription:
      'Browse our selection of laptops and computers. Find the perfect device for your needs with free delivery.',
    backgroundImage: 'https://example.com/images/laptops-bg.jpg',
    backgroundImageAlt: 'A modern laptop on a desk',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Smartphones',
    slug: 'smartphones',
    description:
      'The latest smartphones from top brands, including iPhones, Samsung Galaxy, and Google Pixel.',
    metadata: {
      color: 'darkblue',
    },
    seoSlug: 'latest-smartphones',
    seoTitle: 'New Smartphones 2025 | Samsung, Apple',
    seoDescription:
      'Shop the newest smartphones with advanced features and powerful cameras. Unlocked and contract-free options available.',
    backgroundImage: 'https://example.com/images/smartphones-bg.jpg',
    backgroundImageAlt: 'Three smartphones on a table',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Home Appliances',
    slug: 'home-appliances',
    description:
      'Upgrade your home with smart and efficient appliances, from refrigerators to washing machines.',
    metadata: {
      featured: 'true',
      display_order: '2',
    },
    seoSlug: 'home-appliances-store',
    seoTitle: 'Kitchen & Home Appliances | Top Brands',
    seoDescription:
      'Find refrigerators, washing machines, and small kitchen appliances to make your life easier.',
    backgroundImage: 'https://example.com/images/appliances-bg.jpg',
    backgroundImageAlt: 'A modern kitchen with appliances',
    isActive: true,
  },
  {
    name: 'Books',
    slug: 'books',
    description:
      "Explore new worlds with our extensive collection of fiction, non-fiction, and children's books.",
    metadata: {
      featured: 'true',
      display_order: '3',
    },
    seoSlug: 'buy-books-online',
    seoTitle: 'Bestselling Books Online | All Genres',
    seoDescription:
      'Shop a wide selection of books. Get the latest bestsellers and classic novels with free shipping.',
    backgroundImage: 'https://example.com/images/books-bg.jpg',
    backgroundImageAlt: 'A stack of books',
    isActive: true,
  },
  {
    name: 'Fantasy',
    slug: 'fantasy',
    description:
      'Dive into magical realms and epic adventures with our fantasy book collection.',
    metadata: {
      genre: 'fantasy',
    },
    seoSlug: 'fantasy-books',
    seoTitle: 'Epic Fantasy Books | Read Now',
    seoDescription:
      'Discover epic fantasy sagas and standalone novels from your favorite authors.',
    backgroundImage: 'https://example.com/images/fantasy-bg.jpg',
    backgroundImageAlt: 'A magical forest scene',
    parentId: 'parentId_of_Books',
    isActive: true,
  },
  {
    name: 'Science Fiction',
    slug: 'science-fiction',
    description:
      'Explore futuristic worlds and mind-bending concepts in our sci-fi section.',
    metadata: {
      genre: 'sci-fi',
    },
    seoSlug: 'sci-fi-books',
    seoTitle: 'Science Fiction Novels | Space & Time',
    seoDescription:
      'Find your next great read in our science fiction collection. From space operas to dystopian futures.',
    backgroundImage: 'https://example.com/images/scifi-bg.jpg',
    backgroundImageAlt: 'A futuristic city skyline',
    parentId: 'parentId_of_Books',
    isActive: true,
  },
  {
    name: 'Fashion',
    slug: 'fashion',
    description:
      'Stay trendy with the latest clothing, shoes, and accessories for men, women, and children.',
    metadata: {
      featured: 'true',
      display_order: '4',
    },
    seoSlug: 'fashion-trends',
    seoTitle: 'Shop the Latest Fashion & Apparel',
    seoDescription:
      "Browse our new arrivals in men's, women's, and kids' fashion. Get the perfect outfit for any occasion.",
    backgroundImage: 'https://example.com/images/fashion-bg.jpg',
    backgroundImageAlt: 'A model wearing stylish clothes',
    isActive: true,
  },
  {
    name: "Women's Clothing",
    slug: 'womens-clothing',
    description: "Dresses, tops, jeans, and more for every woman's wardrobe.",
    metadata: {
      gender: 'female',
    },
    seoSlug: 'womens-clothing-store',
    seoTitle: "Women's Clothing | Dresses, Tops, & More",
    seoDescription:
      "Shop our collection of women's apparel for all seasons and styles. New items added daily.",
    backgroundImage: 'https://example.com/images/womens-bg.jpg',
    backgroundImageAlt: "A rack of women's dresses",
    parentId: 'parentId_of_Fashion',
    isActive: true,
  },
  {
    name: "Men's Clothing",
    slug: 'mens-clothing',
    description:
      'Stylish and comfortable clothing for men, from casual wear to formal attire.',
    metadata: {
      gender: 'male',
    },
    seoSlug: 'mens-clothing-store',
    seoTitle: "Men's Clothing | Shirts, Jeans, & Jackets",
    seoDescription:
      "Find the latest trends in men's fashion. Shirts, trousers, and accessories for a modern look.",
    backgroundImage: 'https://example.com/images/mens-bg.jpg',
    backgroundImageAlt: 'A stylish man in a jacket',
    parentId: 'parentId_of_Fashion',
    isActive: true,
  },
  {
    name: 'Health & Beauty',
    slug: 'health-beauty',
    description:
      'Essential products for your health and beauty routine, including skincare, makeup, and vitamins.',
    metadata: {
      featured: 'true',
      display_order: '5',
    },
    seoSlug: 'health-and-beauty-products',
    seoTitle: 'Skincare, Makeup & Wellness Products',
    seoDescription:
      'Shop a wide range of health and beauty items. From skincare to vitamins, find everything you need.',
    backgroundImage: 'https://example.com/images/beauty-bg.jpg',
    backgroundImageAlt: 'Various skincare products on a shelf',
    isActive: true,
  },
  {
    name: 'Skincare',
    slug: 'skincare',
    description:
      'Serums, cleansers, and moisturizers for a radiant and healthy complexion.',
    metadata: {
      product_type: 'skincare',
    },
    seoSlug: 'skincare-products',
    seoTitle: 'Best Skincare Brands | Serums & Creams',
    seoDescription:
      'Explore our collection of skincare products for all skin types. Achieve a glowing complexion.',
    backgroundImage: 'https://example.com/images/skincare-bg.jpg',
    backgroundImageAlt: 'A bottle of serum',
    parentId: 'parentId_of_Health_and_Beauty',
    isActive: true,
  },
  {
    name: 'Makeup',
    slug: 'makeup',
    description:
      'Foundations, lipsticks, and eye palettes to enhance your natural beauty.',
    metadata: {
      product_type: 'makeup',
    },
    seoSlug: 'makeup-store',
    seoTitle: 'Makeup Online | Foundation, Lipstick, etc.',
    seoDescription:
      'Shop our collection of high-quality makeup. Find foundations, lipsticks, and more for every look.',
    backgroundImage: 'https://example.com/images/makeup-bg.jpg',
    backgroundImageAlt: 'Makeup brushes and products',
    parentId: 'parentId_of_Health_and_Beauty',
    isActive: true,
  },
  {
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description:
      'Gear up for your next adventure with our sports equipment and outdoor gear.',
    metadata: {
      featured: 'true',
      display_order: '6',
    },
    seoSlug: 'sports-and-outdoors-gear',
    seoTitle: 'Sports Equipment & Outdoor Gear | Shop Now',
    seoDescription:
      'Find everything you need for sports and outdoor activities. From camping to running, we have you covered.',
    backgroundImage: 'https://example.com/images/sports-bg.jpg',
    backgroundImageAlt: 'A person hiking in the mountains',
    isActive: true,
  },
  {
    name: 'Camping & Hiking',
    slug: 'camping-hiking',
    description:
      'Tents, sleeping bags, and equipment for your next camping trip.',
    metadata: {
      activity: 'outdoor',
    },
    seoSlug: 'camping-and-hiking-gear',
    seoTitle: 'Camping Gear & Hiking Supplies',
    seoDescription:
      'Get ready for your outdoor adventure with our high-quality camping and hiking gear.',
    backgroundImage: 'https://example.com/images/camping-bg.jpg',
    backgroundImageAlt: 'A tent in a scenic landscape',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Fitness',
    slug: 'fitness',
    description:
      'Workout clothes, supplements, and gym equipment to help you achieve your fitness goals.',
    metadata: {
      activity: 'indoor',
    },
    seoSlug: 'fitness-equipment-clothing',
    seoTitle: 'Gym Equipment & Workout Clothes',
    seoDescription:
      'Shop fitness apparel, supplements, and workout gear. Stay healthy and active with our products.',
    backgroundImage: 'https://example.com/images/fitness-bg.jpg',
    backgroundImageAlt: 'Dumbbells and a water bottle',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Toys & Games',
    slug: 'toys-games',
    description:
      'Fun toys and engaging games for all ages, from classic board games to modern video games.',
    metadata: {
      featured: 'false',
    },
    seoSlug: 'toys-and-games',
    seoTitle: 'Toys & Board Games for Kids and Adults',
    seoDescription:
      'Explore our fun collection of toys and games for the whole family. Find the perfect gift.',
    backgroundImage: 'https://example.com/images/toys-bg.jpg',
    backgroundImageAlt: 'A collection of colorful toys',
    isActive: true,
  },
  {
    name: 'Board Games',
    slug: 'board-games',
    description:
      'Strategy games, party games, and classic board games for family game night.',
    metadata: {
      type: 'board-game',
    },
    seoSlug: 'board-games-online',
    seoTitle: 'Best Board Games | Family & Strategy Games',
    seoDescription:
      'Find classic and new board games. Perfect for a fun game night with friends and family.',
    backgroundImage: 'https://example.com/images/boardgames-bg.jpg',
    backgroundImageAlt: 'People playing a board game',
    parentId: 'parentId_of_Toys_and_Games',
    isActive: true,
  },
  {
    name: 'Video Games',
    slug: 'video-games',
    description: 'The latest video games for all major consoles and PC.',
    metadata: {
      type: 'video-game',
    },
    seoSlug: 'video-games-store',
    seoTitle: 'Video Games for PS5, Xbox, PC | New Releases',
    seoDescription:
      'Get new release video games and consoles. Shop for all platforms and genres.',
    backgroundImage: 'https://example.com/images/videogames-bg.jpg',
    backgroundImageAlt: 'A game controller',
    parentId: 'parentId_of_Toys_and_Games',
    isActive: true,
  },
  {
    name: 'Home & Garden',
    slug: 'home-garden',
    description:
      'Everything you need to decorate and maintain your home and garden.',
    metadata: {
      featured: 'false',
    },
    seoSlug: 'home-and-garden-supplies',
    seoTitle: 'Home Decor, Furniture & Garden Tools',
    seoDescription:
      'Shop for furniture, home decor, and garden tools. Make your home beautiful inside and out.',
    backgroundImage: 'https://example.com/images/garden-bg.jpg',
    backgroundImageAlt: 'A beautiful garden with flowers',
    isActive: true,
  },
  {
    name: 'Furniture',
    slug: 'furniture',
    description:
      'Sofas, chairs, tables, and more to furnish your living spaces.',
    metadata: {
      category: 'furniture',
    },
    seoSlug: 'buy-furniture-online',
    seoTitle: 'Modern Furniture for Sale | Living Room & Bedroom',
    seoDescription:
      'Find stylish and affordable furniture for your home. Sofas, beds, tables, and more.',
    backgroundImage: 'https://example.com/images/furniture-bg.jpg',
    backgroundImageAlt: 'A modern living room with a sofa',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Kitchenware',
    slug: 'kitchenware',
    description: 'Pots, pans, utensils, and other essentials for your kitchen.',
    metadata: {
      category: 'kitchen',
    },
    seoSlug: 'kitchenware-supplies',
    seoTitle: 'Kitchen Supplies & Cookware | Pots & Pans',
    seoDescription:
      'Equip your kitchen with high-quality cookware and utensils. Perfect for every home chef.',
    backgroundImage: 'https://example.com/images/kitchenware-bg.jpg',
    backgroundImageAlt: 'Various cooking pots',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Garden Tools',
    slug: 'garden-tools',
    description: 'Essential tools for gardening and lawn care.',
    metadata: {
      category: 'garden',
    },
    seoSlug: 'garden-tools-and-equipment',
    seoTitle: 'Garden Tools for Sale | Shovels & Pruners',
    seoDescription:
      'Get all the tools you need for gardening. Shovels, rakes, and pruners for a perfect garden.',
    backgroundImage: 'https://example.com/images/garden-tools-bg.jpg',
    backgroundImageAlt: 'Gardening gloves and tools',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Automotive',
    slug: 'automotive',
    description: 'Parts, accessories, and tools for all your automotive needs.',
    metadata: {
      featured: 'false',
    },
    seoSlug: 'automotive-parts-accessories',
    seoTitle: 'Car Parts, Accessories & Tools',
    seoDescription:
      'Find everything for your car. From engine parts to accessories, we have you covered.',
    backgroundImage: 'https://example.com/images/automotive-bg.jpg',
    backgroundImageAlt: 'A car engine',
    isActive: true,
  },
  {
    name: 'Car Accessories',
    slug: 'car-accessories',
    description: 'Interior and exterior accessories to customize your car.',
    metadata: {
      type: 'accessory',
    },
    seoSlug: 'car-interior-accessories',
    seoTitle: 'Car Accessories | Seat Covers & Mats',
    seoDescription:
      'Customize your car with our wide selection of accessories. From seat covers to phone holders.',
    backgroundImage: 'https://example.com/images/car-acc-bg.jpg',
    backgroundImageAlt: 'A car dashboard',
    parentId: 'parentId_of_Automotive',
    isActive: true,
  },
  {
    name: 'Tools & Equipment',
    slug: 'tools-equipment',
    description:
      'Power tools, hand tools, and workshop equipment for professionals and DIY enthusiasts.',
    metadata: null,
    seoSlug: 'power-tools-online',
    seoTitle: 'Power Tools & Hand Tools | Shop Now',
    seoDescription:
      'Find drills, saws, wrenches, and more. High-quality tools for every project.',
    backgroundImage: 'https://example.com/images/tools-bg.jpg',
    backgroundImageAlt: 'A collection of hand tools',
    isActive: true,
  },
  {
    name: 'Power Tools',
    slug: 'power-tools',
    description: 'Drills, saws, and sanders for any job.',
    metadata: {
      type: 'power',
    },
    seoSlug: 'buy-power-tools',
    seoTitle: 'Drills, Saws & Sanders | Power Tools',
    seoDescription:
      'Browse our selection of power tools. From cordless drills to circular saws, find what you need.',
    backgroundImage: 'https://example.com/images/powertools-bg.jpg',
    backgroundImageAlt: 'A power drill',
    parentId: 'parentId_of_Tools_and_Equipment',
    isActive: true,
  },
  {
    name: 'Hand Tools',
    slug: 'hand-tools',
    description: 'Wrenches, hammers, and screwdrivers for every toolbox.',
    metadata: {
      type: 'hand',
    },
    seoSlug: 'hand-tools-set',
    seoTitle: 'Hand Tools | Wrenches & Screwdrivers',
    seoDescription:
      'Shop for hand tools for your home or workshop. From hammers to pliers, we have it all.',
    backgroundImage: 'https://example.com/images/handtools-bg.jpg',
    backgroundImageAlt: 'A set of screwdrivers',
    parentId: 'parentId_of_Tools_and_Equipment',
    isActive: true,
  },
  {
    name: 'Pet Supplies',
    slug: 'pet-supplies',
    description: 'Everything your furry, feathery, or scaly friend needs.',
    metadata: null,
    seoSlug: 'pet-supplies-store',
    seoTitle: 'Dog Food, Cat Toys & Pet Accessories',
    seoDescription:
      'Shop for pet food, toys, and accessories for dogs, cats, and other pets.',
    backgroundImage: 'https://example.com/images/pets-bg.jpg',
    backgroundImageAlt: 'A dog and a cat',
    isActive: true,
  },
  {
    name: 'Dog Supplies',
    slug: 'dog-supplies',
    description: 'Food, toys, and beds for your dog.',
    metadata: {
      animal: 'dog',
    },
    seoSlug: 'dog-food-and-toys',
    seoTitle: 'Dog Supplies Online | Food & Treats',
    seoDescription:
      'Find the best food, treats, and toys for your canine companion. Happy pet, happy life.',
    backgroundImage: 'https://example.com/images/dog-bg.jpg',
    backgroundImageAlt: 'A playful dog',
    parentId: 'parentId_of_Pet_Supplies',
    isActive: true,
  },
  {
    name: 'Cat Supplies',
    slug: 'cat-supplies',
    description: 'Food, toys, and litter for your cat.',
    metadata: {
      animal: 'cat',
    },
    seoSlug: 'cat-food-and-litter',
    seoTitle: 'Cat Supplies | Food, Litter & Toys',
    seoDescription:
      'Shop for cat food, litter, and fun toys. Keep your feline friend happy and healthy.',
    backgroundImage: 'https://example.com/images/cat-bg.jpg',
    backgroundImageAlt: 'A curious cat',
    parentId: 'parentId_of_Pet_Supplies',
    isActive: true,
  },
  {
    name: 'Music',
    slug: 'music',
    description: 'Vinyl records, CDs, and instruments for music lovers.',
    metadata: null,
    seoSlug: 'music-records-instruments',
    seoTitle: 'Vinyl Records, CDs & Musical Instruments',
    seoDescription:
      'Explore our collection of music in various formats and find instruments for all skill levels.',
    backgroundImage: 'https://example.com/images/music-bg.jpg',
    backgroundImageAlt: 'A vinyl record player',
    isActive: true,
  },
  {
    name: 'Vinyl Records',
    slug: 'vinyl-records',
    description: 'Classic and new releases on vinyl.',
    metadata: {
      format: 'vinyl',
    },
    seoSlug: 'buy-vinyl-records',
    seoTitle: 'Vinyl Records for Sale | Classic & New',
    seoDescription:
      'Browse our vinyl record collection. From classic rock to modern pop, find your favorite albums.',
    backgroundImage: 'https://example.com/images/vinyl-bg.jpg',
    backgroundImageAlt: 'A vinyl record',
    parentId: 'parentId_of_Music',
    isActive: true,
  },
  {
    name: 'Musical Instruments',
    slug: 'musical-instruments',
    description: 'Guitars, keyboards, and drums for aspiring musicians.',
    metadata: {
      format: 'instrument',
    },
    seoSlug: 'musical-instruments-store',
    seoTitle: 'Guitars, Keyboards & Drums | Shop Instruments',
    seoDescription:
      'Find instruments for all skill levels. Guitars, keyboards, drums, and more.',
    backgroundImage: 'https://example.com/images/instruments-bg.jpg',
    backgroundImageAlt: 'A guitar and a keyboard',
    parentId: 'parentId_of_Music',
    isActive: true,
  },
  {
    name: 'Food & Grocery',
    slug: 'food-grocery',
    description: 'Fresh produce, pantry staples, and gourmet food items.',
    metadata: null,
    seoSlug: 'online-food-grocery',
    seoTitle: 'Buy Food & Groceries Online | Fresh & Organic',
    seoDescription:
      'Shop for fresh produce, snacks, and pantry essentials. Delivered to your doorstep.',
    backgroundImage: 'https://example.com/images/food-bg.jpg',
    backgroundImageAlt: 'Fresh vegetables in a basket',
    isActive: true,
  },
  {
    name: 'Snacks & Confectionery',
    slug: 'snacks-confectionery',
    description: 'Chips, chocolates, and candies for a sweet treat.',
    metadata: {
      type: 'snack',
    },
    seoSlug: 'snacks-and-candy',
    seoTitle: 'Chips, Chocolates & Sweets',
    seoDescription:
      'Satisfy your cravings with our delicious snacks and sweets. Find your favorite brands.',
    backgroundImage: 'https://example.com/images/snacks-bg.jpg',
    backgroundImageAlt: 'A bowl of chips',
    parentId: 'parentId_of_Food_and_Grocery',
    isActive: true,
  },
  {
    name: 'Beverages',
    slug: 'beverages',
    description: 'Coffee, tea, soft drinks, and juices.',
    metadata: {
      type: 'drink',
    },
    seoSlug: 'beverages-online',
    seoTitle: 'Coffee, Tea & Juices | Shop Drinks',
    seoDescription:
      'Stay hydrated with our selection of beverages. Coffee, tea, and refreshing juices.',
    backgroundImage: 'https://example.com/images/drinks-bg.jpg',
    backgroundImageAlt: 'A cup of coffee',
    parentId: 'parentId_of_Food_and_Grocery',
    isActive: true,
  },
  {
    name: 'Jewelry',
    slug: 'jewelry',
    description: 'Elegant rings, necklaces, and earrings for every occasion.',
    metadata: null,
    seoSlug: 'jewelry-online-store',
    seoTitle: 'Rings, Necklaces & Earrings | Fine Jewelry',
    seoDescription:
      'Find the perfect piece of jewelry. From elegant necklaces to stunning rings, we have it all.',
    backgroundImage: 'https://example.com/images/jewelry-bg.jpg',
    backgroundImageAlt: 'A diamond ring',
    isActive: true,
  },
  {
    name: 'Rings',
    slug: 'rings',
    description: 'Wedding rings, engagement rings, and fashion rings.',
    metadata: {
      item: 'ring',
    },
    seoSlug: 'rings-for-sale',
    seoTitle: 'Wedding & Fashion Rings | Shop Online',
    seoDescription:
      'Explore our beautiful collection of rings. Find the perfect ring for any special moment.',
    backgroundImage: 'https://example.com/images/rings-bg.jpg',
    backgroundImageAlt: 'A hand with a ring',
    parentId: 'parentId_of_Jewelry',
    isActive: true,
  },
  {
    name: 'Necklaces',
    slug: 'necklaces',
    description: 'Gold, silver, and diamond necklaces.',
    metadata: {
      item: 'necklace',
    },
    seoSlug: 'necklaces-for-sale',
    seoTitle: 'Gold & Silver Necklaces | Pendants',
    seoDescription:
      'Browse our selection of necklaces and pendants. Perfect for adding a touch of elegance.',
    backgroundImage: 'https://example.com/images/necklaces-bg.jpg',
    backgroundImageAlt: 'A necklace on a model',
    parentId: 'parentId_of_Jewelry',
    isActive: true,
  },
  {
    name: 'Eyewear',
    slug: 'eyewear',
    description: 'Stylish sunglasses and prescription glasses.',
    metadata: null,
    seoSlug: 'eyewear-online-store',
    seoTitle: 'Sunglasses & Eyeglasses | Designer Brands',
    seoDescription:
      'Find your next pair of glasses. Shop for sunglasses and prescription glasses from top brands.',
    backgroundImage: 'https://example.com/images/eyewear-bg.jpg',
    backgroundImageAlt: 'A pair of sunglasses',
    isActive: true,
  },
  {
    name: 'Sunglasses',
    slug: 'sunglasses',
    description: 'UV protection and polarized sunglasses.',
    metadata: {
      type: 'sunglasses',
    },
    seoSlug: 'buy-sunglasses-online',
    seoTitle: 'Polarized Sunglasses | UV Protection',
    seoDescription:
      'Protect your eyes with our stylish sunglasses. Find polarized and UV protection lenses.',
    backgroundImage: 'https://example.com/images/sunglasses-bg.jpg',
    backgroundImageAlt: 'A woman wearing sunglasses',
    parentId: 'parentId_of_Eyewear',
    isActive: true,
  },
  {
    name: 'Prescription Glasses',
    slug: 'prescription-glasses',
    description: 'Frames and lenses for your vision needs.',
    metadata: {
      type: 'prescription',
    },
    seoSlug: 'prescription-glasses-online',
    seoTitle: 'Eyeglasses Online | Prescription Lenses',
    seoDescription:
      'Order prescription glasses online. Choose from a wide variety of frames and lenses.',
    backgroundImage: 'https://example.com/images/glasses-bg.jpg',
    backgroundImageAlt: 'A person wearing glasses',
    parentId: 'parentId_of_Eyewear',
    isActive: true,
  },
  {
    name: 'Baby & Toddler',
    slug: 'baby-toddler',
    description: 'Everything for babies and toddlers, from diapers to toys.',
    metadata: null,
    seoSlug: 'baby-and-toddler-supplies',
    seoTitle: 'Baby Clothes, Toys & Diapers | Shop Now',
    seoDescription:
      'Find all the essentials for your little one. Diapers, clothes, toys, and feeding supplies.',
    backgroundImage: 'https://example.com/images/baby-bg.jpg',
    backgroundImageAlt: 'A sleeping baby',
    isActive: true,
  },
  {
    name: 'Diapers',
    slug: 'diapers',
    description: 'Disposable and cloth diapers for all ages.',
    metadata: {
      product: 'diapers',
    },
    seoSlug: 'diapers-for-sale',
    seoTitle: 'Diapers Online | Disposable & Cloth',
    seoDescription:
      'Stock up on diapers for your baby. Find disposable and cloth diapers from top brands.',
    backgroundImage: 'https://example.com/images/diapers-bg.jpg',
    backgroundImageAlt: 'A stack of diapers',
    parentId: 'parentId_of_Baby_and_Toddler',
    isActive: true,
  },
  {
    name: 'Baby Toys',
    slug: 'baby-toys',
    description: 'Educational and fun toys for babies.',
    metadata: {
      product: 'toy',
    },
    seoSlug: 'baby-toys-online',
    seoTitle: 'Educational Baby Toys | Shop Now',
    seoDescription:
      'Find safe and engaging toys for your baby. Perfect for playtime and development.',
    backgroundImage: 'https://example.com/images/baby-toys-bg.jpg',
    backgroundImageAlt: 'A colorful baby toy',
    parentId: 'parentId_of_Baby_and_Toddler',
    isActive: true,
  },
  {
    name: 'Arts & Crafts',
    slug: 'arts-crafts',
    description: 'Supplies for painting, drawing, and crafting.',
    metadata: null,
    seoSlug: 'arts-and-crafts-supplies',
    seoTitle: 'Art Supplies & Craft Kits | Shop Online',
    seoDescription:
      'Unleash your creativity with our art and craft supplies. Paints, brushes, and more.',
    backgroundImage: 'https://example.com/images/art-bg.jpg',
    backgroundImageAlt: 'Paint brushes and colors',
    isActive: true,
  },
  {
    name: 'Painting',
    slug: 'painting',
    description: 'Paints, canvases, and brushes for painters.',
    metadata: {
      activity: 'painting',
    },
    seoSlug: 'painting-supplies',
    seoTitle: 'Paints, Brushes & Canvases | Art Supplies',
    seoDescription:
      'Shop for painting supplies. Find acrylics, watercolors, and canvases for your next masterpiece.',
    backgroundImage: 'https://example.com/images/painting-bg.jpg',
    backgroundImageAlt: 'A person painting on a canvas',
    parentId: 'parentId_of_Arts_and_Crafts',
    isActive: true,
  },
  {
    name: 'Drawing',
    slug: 'drawing',
    description: 'Pencils, sketchbooks, and drawing kits.',
    metadata: {
      activity: 'drawing',
    },
    seoSlug: 'drawing-supplies',
    seoTitle: 'Pencils, Sketchbooks & Markers | Drawing',
    seoDescription:
      'Get all the supplies for drawing. Pencils, markers, and sketchbooks for artists of all levels.',
    backgroundImage: 'https://example.com/images/drawing-bg.jpg',
    backgroundImageAlt: 'A person drawing with a pencil',
    parentId: 'parentId_of_Arts_and_Crafts',
    isActive: true,
  },
  {
    name: 'Office Supplies',
    slug: 'office-supplies',
    description: 'Paper, pens, and organizational tools for your office.',
    metadata: null,
    seoSlug: 'office-supplies-online',
    seoTitle: 'Paper, Pens & Office Furniture',
    seoDescription:
      'Equip your office with essential supplies. From paper to pens, we have it all.',
    backgroundImage: 'https://example.com/images/office-bg.jpg',
    backgroundImageAlt: 'An organized desk',
    isActive: true,
  },
  {
    name: 'Writing Instruments',
    slug: 'writing-instruments',
    description: 'Pens, pencils, and markers.',
    metadata: {
      type: 'writing',
    },
    seoSlug: 'pens-and-pencils',
    seoTitle: 'Pens, Pencils & Markers | Writing Supplies',
    seoDescription:
      'Find the perfect writing instrument for your needs. Pens, pencils, and highlighters.',
    backgroundImage: 'https://example.com/images/pens-bg.jpg',
    backgroundImageAlt: 'A collection of colorful pens',
    parentId: 'parentId_of_Office_Supplies',
    isActive: true,
  },
  {
    name: 'Paper & Notebooks',
    slug: 'paper-notebooks',
    description: 'Printer paper, notebooks, and notepads.',
    metadata: {
      type: 'paper',
    },
    seoSlug: 'notebooks-and-paper',
    seoTitle: 'Printer Paper & Notebooks | Office Supplies',
    seoDescription:
      'Stock up on paper and notebooks for your office. High-quality paper for all your needs.',
    backgroundImage: 'https://example.com/images/paper-bg.jpg',
    backgroundImageAlt: 'A stack of notebooks',
    parentId: 'parentId_of_Office_Supplies',
    isActive: true,
  },
  {
    name: 'Software',
    slug: 'software',
    description: 'Operating systems, office suites, and creative software.',
    metadata: null,
    seoSlug: 'software-online',
    seoTitle: 'Operating Systems & Productivity Software',
    seoDescription:
      'Download software for your PC or Mac. Find operating systems, office suites, and more.',
    backgroundImage: 'https://example.com/images/software-bg.jpg',
    backgroundImageAlt: 'A computer screen with code',
    isActive: true,
  },
  {
    name: 'Operating Systems',
    slug: 'operating-systems',
    description: 'Windows, macOS, and Linux operating systems.',
    metadata: {
      type: 'os',
    },
    seoSlug: 'buy-operating-systems',
    seoTitle: 'Windows, macOS & Linux | OS',
    seoDescription:
      'Get the latest operating systems for your computer. Easy to install and use.',
    backgroundImage: 'https://example.com/images/os-bg.jpg',
    backgroundImageAlt: 'A logo of an operating system',
    parentId: 'parentId_of_Software',
    isActive: true,
  },
  {
    name: 'Productivity Software',
    slug: 'productivity-software',
    description: 'Office suites, project management tools, and more.',
    metadata: {
      type: 'productivity',
    },
    seoSlug: 'productivity-software-tools',
    seoTitle: 'Office Suites & Project Management Tools',
    seoDescription:
      'Boost your productivity with our software. Find tools for work and daily life.',
    backgroundImage: 'https://example.com/images/productivity-bg.jpg',
    backgroundImageAlt: 'A spreadsheet on a screen',
    parentId: 'parentId_of_Software',
    isActive: true,
  },
  {
    name: 'Cameras',
    slug: 'cameras',
    description: 'Digital cameras, mirrorless cameras, and lenses.',
    metadata: {
      category: 'photo',
    },
    seoSlug: 'buy-cameras-online',
    seoTitle: 'Digital Cameras & Lenses | Shop Now',
    seoDescription:
      'Capture beautiful moments with our cameras and lenses. Find DSLRs, mirrorless, and more.',
    backgroundImage: 'https://example.com/images/camera-bg.jpg',
    backgroundImageAlt: 'A digital camera',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Televisions',
    slug: 'televisions',
    description: '4K, QLED, and OLED TVs for a cinematic experience.',
    metadata: {
      category: 'home-entertainment',
    },
    seoSlug: 'buy-televisions-online',
    seoTitle: '4K & Smart TVs | Shop Televisions',
    seoDescription:
      'Experience stunning visuals with our 4K and Smart TVs. Perfect for your home entertainment.',
    backgroundImage: 'https://example.com/images/tv-bg.jpg',
    backgroundImageAlt: 'A large television screen',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Headphones',
    slug: 'headphones',
    description: 'Noise-cancelling, wireless, and over-ear headphones.',
    metadata: {
      category: 'audio',
    },
    seoSlug: 'buy-headphones-online',
    seoTitle: 'Wireless Headphones & Earbuds',
    seoDescription:
      'Immerse yourself in music with our high-quality headphones. Find wireless and noise-cancelling options.',
    backgroundImage: 'https://example.com/images/headphones-bg.jpg',
    backgroundImageAlt: 'A pair of headphones',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Refrigerators',
    slug: 'refrigerators',
    description: 'Energy-efficient refrigerators with advanced features.',
    metadata: {
      type: 'refrigerator',
    },
    seoSlug: 'refrigerators-for-sale',
    seoTitle: 'Refrigerators | French Door & Side-by-Side',
    seoDescription:
      'Find the perfect refrigerator for your kitchen. Energy-efficient and spacious designs.',
    backgroundImage: 'https://example.com/images/fridge-bg.jpg',
    backgroundImageAlt: 'A modern refrigerator',
    parentId: 'parentId_of_Home_Appliances',
    isActive: true,
  },
  {
    name: 'Washing Machines',
    slug: 'washing-machines',
    description: 'Top-load and front-load washing machines.',
    metadata: {
      type: 'washer',
    },
    seoSlug: 'washing-machines-online',
    seoTitle: 'Washing Machines | Top & Front Load',
    seoDescription:
      'Shop for washing machines with powerful cleaning cycles. Save time and energy on laundry day.',
    backgroundImage: 'https://example.com/images/washer-bg.jpg',
    backgroundImageAlt: 'A washing machine in a laundry room',
    parentId: 'parentId_of_Home_Appliances',
    isActive: true,
  },
  {
    name: 'Small Kitchen Appliances',
    slug: 'small-kitchen-appliances',
    description:
      'Blenders, toasters, and coffee makers for your kitchen counter.',
    metadata: {
      type: 'small-appliance',
    },
    seoSlug: 'small-kitchen-appliances',
    seoTitle: 'Blenders, Toasters & Coffee Makers',
    seoDescription:
      'Find blenders, toasters, and coffee makers. Make cooking and brewing easier.',
    backgroundImage: 'https://example.com/images/blender-bg.jpg',
    backgroundImageAlt: 'A blender on a kitchen counter',
    parentId: 'parentId_of_Home_Appliances',
    isActive: true,
  },
  {
    name: 'Non-Fiction',
    slug: 'non-fiction',
    description: 'Biographies, history, and science books.',
    metadata: {
      genre: 'non-fiction',
    },
    seoSlug: 'non-fiction-books',
    seoTitle: 'Biographies, History & Science Books',
    seoDescription:
      'Learn something new with our non-fiction collection. Explore history, science, and more.',
    backgroundImage: 'https://example.com/images/non-fiction-bg.jpg',
    backgroundImageAlt: 'A book with a historical photo',
    parentId: 'parentId_of_Books',
    isActive: true,
  },
  {
    name: 'Thriller',
    slug: 'thriller',
    description: 'Suspenseful and thrilling novels.',
    metadata: {
      genre: 'thriller',
    },
    seoSlug: 'thriller-books',
    seoTitle: 'Suspense & Thriller Novels | Bestsellers',
    seoDescription:
      'Get your adrenaline pumping with our thriller novels. Find gripping stories and mysteries.',
    backgroundImage: 'https://example.com/images/thriller-bg.jpg',
    backgroundImageAlt: 'A dark, mysterious alleyway',
    parentId: 'parentId_of_Books',
    isActive: true,
  },
  {
    name: 'Dresses',
    slug: 'dresses',
    description: 'Elegant dresses for all occasions.',
    metadata: {
      item: 'dress',
    },
    seoSlug: 'dresses-for-women',
    seoTitle: "Women's Dresses | Casual & Formal",
    seoDescription:
      'Find the perfect dress for any event. From casual to formal, we have a style for you.',
    backgroundImage: 'https://example.com/images/dress-bg.jpg',
    backgroundImageAlt: 'A woman in a red dress',
    parentId: 'parentId_of_Womens_Clothing',
    isActive: true,
  },
  {
    name: 'Jeans',
    slug: 'jeans',
    description: 'Denim jeans for men and women.',
    metadata: {
      item: 'jeans',
    },
    seoSlug: 'jeans-for-sale',
    seoTitle: "Men's & Women's Jeans | Denim Styles",
    seoDescription:
      'Shop our collection of stylish and comfortable denim jeans. All sizes and fits available.',
    backgroundImage: 'https://example.com/images/jeans-bg.jpg',
    backgroundImageAlt: 'A pair of denim jeans',
    parentId: 'parentId_of_Mens_Clothing',
    isActive: true,
  },
  {
    name: 'T-Shirts',
    slug: 't-shirts',
    description: 'Casual t-shirts for everyday wear.',
    metadata: {
      item: 't-shirt',
    },
    seoSlug: 't-shirts-online',
    seoTitle: "Men's T-Shirts | Graphic & Plain",
    seoDescription:
      'Find comfortable and stylish t-shirts for men. Perfect for any casual outfit.',
    backgroundImage: 'https://example.com/images/tshirt-bg.jpg',
    backgroundImageAlt: 'A stack of folded t-shirts',
    parentId: 'parentId_of_Mens_Clothing',
    isActive: true,
  },
  {
    name: 'Hats',
    slug: 'hats',
    description: 'Hats for all seasons and styles.',
    metadata: {
      item: 'hat',
    },
    seoSlug: 'hats-for-sale',
    seoTitle: 'Hats & Caps | Beanies & Baseball Caps',
    seoDescription:
      'Complete your look with our trendy hats and caps. Find beanies, baseball caps, and more.',
    backgroundImage: 'https://example.com/images/hats-bg.jpg',
    backgroundImageAlt: 'Various hats on a shelf',
    parentId: 'parentId_of_Fashion',
    isActive: true,
  },
  {
    name: 'Fragrances',
    slug: 'fragrances',
    description: 'Perfumes and colognes for men and women.',
    metadata: {
      type: 'fragrance',
    },
    seoSlug: 'buy-fragrances-online',
    seoTitle: 'Perfume & Cologne | Designer Scents',
    seoDescription:
      'Find your signature scent with our fragrances. From designer perfumes to fresh colognes.',
    backgroundImage: 'https://example.com/images/perfume-bg.jpg',
    backgroundImageAlt: 'A perfume bottle',
    parentId: 'parentId_of_Health_and_Beauty',
    isActive: true,
  },
  {
    name: 'Haircare',
    slug: 'haircare',
    description: 'Shampoos, conditioners, and styling products.',
    metadata: {
      type: 'haircare',
    },
    seoSlug: 'haircare-products',
    seoTitle: 'Shampoo, Conditioner & Hair Styling',
    seoDescription:
      'Nourish your hair with our haircare products. Shampoos, conditioners, and styling tools for all hair types.',
    backgroundImage: 'https://example.com/images/hair-bg.jpg',
    backgroundImageAlt: 'Shampoo and conditioner bottles',
    parentId: 'parentId_of_Health_and_Beauty',
    isActive: true,
  },
  {
    name: 'Supplements',
    slug: 'supplements',
    description: 'Vitamins, minerals, and protein powders.',
    metadata: {
      type: 'supplement',
    },
    seoSlug: 'buy-supplements-online',
    seoTitle: 'Vitamins, Minerals & Protein Powder',
    seoDescription:
      'Boost your health with our supplements. Find vitamins, minerals, and protein powders.',
    backgroundImage: 'https://example.com/images/supplements-bg.jpg',
    backgroundImageAlt: 'A container of protein powder',
    parentId: 'parentId_of_Health_and_Beauty',
    isActive: true,
  },
  {
    name: 'Running',
    slug: 'running',
    description: 'Running shoes, apparel, and accessories.',
    metadata: {
      activity: 'running',
    },
    seoSlug: 'running-gear',
    seoTitle: 'Running Shoes & Apparel | Shop Now',
    seoDescription:
      'Get ready to run with our running gear. Shoes, clothes, and accessories for all runners.',
    backgroundImage: 'https://example.com/images/running-bg.jpg',
    backgroundImageAlt: 'A person running on a trail',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Cycling',
    slug: 'cycling',
    description: 'Bikes, helmets, and cycling apparel.',
    metadata: {
      activity: 'cycling',
    },
    seoSlug: 'cycling-gear',
    seoTitle: 'Bikes, Helmets & Cycling Apparel',
    seoDescription:
      'Hit the road with our cycling gear. Bikes, helmets, and apparel for all cyclists.',
    backgroundImage: 'https://example.com/images/cycling-bg.jpg',
    backgroundImageAlt: 'A person riding a bicycle',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Cooking & Baking',
    slug: 'cooking-baking',
    description: 'Cookbooks, bakeware, and kitchen gadgets.',
    metadata: {
      category: 'kitchen',
    },
    seoSlug: 'cooking-and-baking-supplies',
    seoTitle: 'Cookbooks, Bakeware & Kitchen Gadgets',
    seoDescription:
      'Find everything you need for cooking and baking. Cookbooks, bakeware, and more.',
    backgroundImage: 'https://example.com/images/baking-bg.jpg',
    backgroundImageAlt: 'Ingredients for baking',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Painting Supplies',
    slug: 'painting-supplies',
    description: 'Acrylics, oils, and watercolors.',
    metadata: {
      type: 'paint',
    },
    seoSlug: 'buy-painting-supplies',
    seoTitle: 'Acrylics, Oils & Watercolors | Art',
    seoDescription:
      'Shop our wide selection of paints and brushes for all your painting needs.',
    backgroundImage: 'https://example.com/images/paints-bg.jpg',
    backgroundImageAlt: 'Tubes of paint',
    parentId: 'parentId_of_Painting',
    isActive: true,
  },
  {
    name: 'Office Furniture',
    slug: 'office-furniture',
    description: 'Desks, chairs, and cabinets for your workspace.',
    metadata: {
      type: 'furniture',
    },
    seoSlug: 'office-furniture-online',
    seoTitle: 'Desks, Chairs & Cabinets | Office',
    seoDescription:
      'Furnish your office with our desks, chairs, and storage solutions.',
    backgroundImage: 'https://example.com/images/office-furniture-bg.jpg',
    backgroundImageAlt: 'A modern office desk',
    parentId: 'parentId_of_Office_Supplies',
    isActive: true,
  },
  {
    name: 'Software Tools',
    slug: 'software-tools',
    description: 'Tools for developers, designers, and creators.',
    metadata: {
      type: 'tool',
    },
    seoSlug: 'developer-software-tools',
    seoTitle: 'Developer & Design Software | Shop Now',
    seoDescription:
      'Find the perfect software tools for your projects. IDEs, design software, and more.',
    backgroundImage: 'https://example.com/images/dev-tools-bg.jpg',
    backgroundImageAlt: 'A person coding on a screen',
    parentId: 'parentId_of_Software',
    isActive: true,
  },
  {
    name: 'Kitchenware Sets',
    slug: 'kitchenware-sets',
    description: 'Complete sets of pots, pans, and utensils.',
    metadata: {
      type: 'set',
    },
    seoSlug: 'cookware-sets',
    seoTitle: 'Pots & Pans Sets | Cookware',
    seoDescription:
      'Get a complete set of kitchenware for your new home. Perfect for every kitchen.',
    backgroundImage: 'https://example.com/images/cookware-set-bg.jpg',
    backgroundImageAlt: 'A set of cooking pots',
    parentId: 'parentId_of_Kitchenware',
    isActive: true,
  },
  {
    name: 'Smart Home',
    slug: 'smart-home',
    description:
      'Smart devices for your home, including lighting and security.',
    metadata: {
      type: 'smart-device',
    },
    seoSlug: 'smart-home-devices',
    seoTitle: 'Smart Home Devices | Lights & Security',
    seoDescription:
      'Control your home with smart devices. Find smart lighting, security cameras, and more.',
    backgroundImage: 'https://example.com/images/smarthome-bg.jpg',
    backgroundImageAlt: 'A smart speaker',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Gaming',
    slug: 'gaming',
    description: 'Gaming consoles, accessories, and PC components.',
    metadata: {
      type: 'gaming',
    },
    seoSlug: 'gaming-consoles-pc-components',
    seoTitle: 'Gaming Consoles, PC Parts & Accessories',
    seoDescription:
      'Build your ultimate gaming setup. Find consoles, graphics cards, and accessories.',
    backgroundImage: 'https://example.com/images/gaming-bg.jpg',
    backgroundImageAlt: 'A gaming setup with a monitor',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Drones',
    slug: 'drones',
    description: 'Drones for photography, videography, and fun.',
    metadata: {
      type: 'drone',
    },
    seoSlug: 'buy-drones-online',
    seoTitle: 'Drones with Camera | Shop Now',
    seoDescription:
      'Capture stunning aerial footage with our drones. Find drones for beginners and professionals.',
    backgroundImage: 'https://example.com/images/drone-bg.jpg',
    backgroundImageAlt: 'A drone flying in the sky',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Computer Peripherals',
    slug: 'computer-peripherals',
    description: 'Mice, keyboards, and monitors.',
    metadata: {
      type: 'peripheral',
    },
    seoSlug: 'computer-mice-keyboards',
    seoTitle: 'Mice, Keyboards & Monitors | PC',
    seoDescription:
      'Upgrade your PC setup with our peripherals. Find ergonomic mice, mechanical keyboards, and more.',
    backgroundImage: 'https://example.com/images/peripherals-bg.jpg',
    backgroundImageAlt: 'A computer keyboard and mouse',
    parentId: 'parentId_of_Laptops_and_Computers',
    isActive: true,
  },
  {
    name: 'Fiction',
    slug: 'fiction',
    description: 'Novels, short stories, and poetry.',
    metadata: {
      genre: 'fiction',
    },
    seoSlug: 'fiction-books',
    seoTitle: 'Novels & Short Stories | Fiction',
    seoDescription:
      'Escape into new worlds with our fiction collection. Bestselling novels and timeless classics.',
    backgroundImage: 'https://example.com/images/fiction-bg.jpg',
    backgroundImageAlt: 'A person reading a book',
    parentId: 'parentId_of_Books',
    isActive: true,
  },
  {
    name: "Children's Books",
    slug: 'childrens-books',
    description: 'Books for kids of all ages.',
    metadata: {
      genre: 'childrens',
    },
    seoSlug: 'childrens-books-online',
    seoTitle: "Kids' Books & Storybooks",
    seoDescription:
      'Find educational and fun books for children. Perfect for bedtime stories and learning.',
    backgroundImage: 'https://example.com/images/kids-books-bg.jpg',
    backgroundImageAlt: "A colorful children's book",
    parentId: 'parentId_of_Books',
    isActive: true,
  },
  {
    name: 'Coats & Jackets',
    slug: 'coats-jackets',
    description: 'Jackets and coats for all seasons.',
    metadata: {
      item: 'jacket',
    },
    seoSlug: 'coats-and-jackets',
    seoTitle: "Men's & Women's Coats | Shop Now",
    seoDescription:
      'Stay warm and stylish with our collection of coats and jackets. For all weather conditions.',
    backgroundImage: 'https://example.com/images/jackets-bg.jpg',
    backgroundImageAlt: 'A leather jacket',
    parentId: 'parentId_of_Fashion',
    isActive: true,
  },
  {
    name: 'Shoes',
    slug: 'shoes',
    description: 'Sneakers, boots, and sandals for men and women.',
    metadata: {
      item: 'shoes',
    },
    seoSlug: 'buy-shoes-online',
    seoTitle: 'Sneakers, Boots & Sandals | Shop Shoes',
    seoDescription:
      'Find the perfect pair of shoes for any occasion. From casual sneakers to elegant boots.',
    backgroundImage: 'https://example.com/images/shoes-bg.jpg',
    backgroundImageAlt: 'A pair of sneakers',
    parentId: 'parentId_of_Fashion',
    isActive: true,
  },
  {
    name: 'Watches',
    slug: 'watches',
    description: 'Smartwatches and analog watches.',
    metadata: {
      item: 'watch',
    },
    seoSlug: 'buy-watches-online',
    seoTitle: 'Smartwatches & Analog Watches',
    seoDescription:
      'Stay on time with our stylish watches. Find smartwatches and classic analog designs.',
    backgroundImage: 'https://example.com/images/watches-bg.jpg',
    backgroundImageAlt: 'A watch on a wrist',
    parentId: 'parentId_of_Fashion',
    isActive: true,
  },
  {
    name: 'Pet Food',
    slug: 'pet-food',
    description: 'Dry food, wet food, and treats for pets.',
    metadata: {
      type: 'food',
    },
    seoSlug: 'pet-food-online',
    seoTitle: 'Dog Food, Cat Food & Treats',
    seoDescription:
      'Shop for nutritious food for your pet. Find dry food, wet food, and healthy treats.',
    backgroundImage: 'https://example.com/images/pet-food-bg.jpg',
    backgroundImageAlt: 'A bowl of pet food',
    parentId: 'parentId_of_Pet_Supplies',
    isActive: true,
  },
  {
    name: 'Toys',
    slug: 'toys',
    description: 'Toys for all ages.',
    metadata: {
      type: 'toy',
    },
    seoSlug: 'toys-for-kids',
    seoTitle: 'Action Figures, Dolls & Puzzles',
    seoDescription:
      'Explore our fun collection of toys for kids. Find action figures, dolls, and puzzles.',
    backgroundImage: 'https://example.com/images/toys-bg2.jpg',
    backgroundImageAlt: 'A pile of toys',
    parentId: 'parentId_of_Toys_and_Games',
    isActive: true,
  },
  {
    name: 'PlayStation',
    slug: 'playstation',
    description: 'PlayStation consoles and games.',
    metadata: {
      platform: 'ps',
    },
    seoSlug: 'playstation-games',
    seoTitle: 'PS5 & PS4 Games | New Releases',
    seoDescription:
      'Shop for the latest PlayStation games and consoles. Get ready to play.',
    backgroundImage: 'https://example.com/images/ps-bg.jpg',
    backgroundImageAlt: 'A PlayStation console',
    parentId: 'parentId_of_Video_Games',
    isActive: true,
  },
  {
    name: 'Xbox',
    slug: 'xbox',
    description: 'Xbox consoles and games.',
    metadata: {
      platform: 'xbox',
    },
    seoSlug: 'xbox-games',
    seoTitle: 'Xbox Series X & S Games',
    seoDescription:
      'Find the latest Xbox games and consoles. Enjoy high-quality gaming experiences.',
    backgroundImage: 'https://example.com/images/xbox-bg.jpg',
    backgroundImageAlt: 'An Xbox console',
    parentId: 'parentId_of_Video_Games',
    isActive: true,
  },
  {
    name: 'Nintendo',
    slug: 'nintendo',
    description: 'Nintendo Switch and games.',
    metadata: {
      platform: 'nintendo',
    },
    seoSlug: 'nintendo-switch-games',
    seoTitle: 'Nintendo Switch Games & Consoles',
    seoDescription:
      'Shop for Nintendo Switch consoles and games. Perfect for on-the-go gaming.',
    backgroundImage: 'https://example.com/images/nintendo-bg.jpg',
    backgroundImageAlt: 'A Nintendo Switch console',
    parentId: 'parentId_of_Video_Games',
    isActive: true,
  },
  {
    name: 'PC Gaming',
    slug: 'pc-gaming',
    description: 'PC games and components.',
    metadata: {
      platform: 'pc',
    },
    seoSlug: 'pc-gaming-components',
    seoTitle: 'PC Games & Graphics Cards',
    seoDescription:
      'Build your powerful PC with our components. Find graphics cards, CPUs, and more.',
    backgroundImage: 'https://example.com/images/pc-bg.jpg',
    backgroundImageAlt: 'A gaming PC setup',
    parentId: 'parentId_of_Video_Games',
    isActive: true,
  },
  {
    name: 'Action Figures',
    slug: 'action-figures',
    description: 'Action figures from your favorite movies and shows.',
    metadata: {
      type: 'action-figure',
    },
    seoSlug: 'action-figures-online',
    seoTitle: 'Action Figures | Marvel, Star Wars & more',
    seoDescription:
      'Collect action figures from movies, comics, and video games. A must-have for fans.',
    backgroundImage: 'https://example.com/images/action-figure-bg.jpg',
    backgroundImageAlt: 'A superhero action figure',
    parentId: 'parentId_of_Toys',
    isActive: true,
  },
  {
    name: 'Building Blocks',
    slug: 'building-blocks',
    description: 'LEGO and other building sets.',
    metadata: {
      type: 'building-blocks',
    },
    seoSlug: 'building-blocks-sets',
    seoTitle: 'LEGO & Building Block Sets',
    seoDescription:
      'Build amazing creations with our building blocks. Perfect for kids and adults.',
    backgroundImage: 'https://example.com/images/blocks-bg.jpg',
    backgroundImageAlt: 'A child playing with building blocks',
    parentId: 'parentId_of_Toys',
    isActive: true,
  },
  {
    name: 'Sofas & Couches',
    slug: 'sofas-couches',
    description: 'Comfortable sofas for your living room.',
    metadata: {
      item: 'sofa',
    },
    seoSlug: 'sofas-and-couches',
    seoTitle: 'Sofas & Couches | Living Room Furniture',
    seoDescription:
      'Find the perfect sofa for your living room. Sectionals, recliners, and more.',
    backgroundImage: 'https://example.com/images/sofa-bg.jpg',
    backgroundImageAlt: 'A modern sofa',
    parentId: 'parentId_of_Furniture',
    isActive: true,
  },
  {
    name: 'Beds & Mattresses',
    slug: 'beds-mattresses',
    description: "Beds and mattresses for a good night's sleep.",
    metadata: {
      item: 'bed',
    },
    seoSlug: 'beds-and-mattresses',
    seoTitle: 'Beds & Mattresses | Shop Bedroom Furniture',
    seoDescription:
      'Upgrade your sleep with our comfortable beds and mattresses. Sweet dreams guaranteed.',
    backgroundImage: 'https://example.com/images/bed-bg.jpg',
    backgroundImageAlt: 'A comfortable bed',
    parentId: 'parentId_of_Furniture',
    isActive: true,
  },
  {
    name: 'Dining Tables',
    slug: 'dining-tables',
    description: 'Dining tables for every home.',
    metadata: {
      item: 'table',
    },
    seoSlug: 'dining-tables-for-sale',
    seoTitle: 'Dining Tables | Kitchen & Dining Room',
    seoDescription:
      'Find the perfect dining table for your home. From rustic to modern designs.',
    backgroundImage: 'https://example.com/images/dining-bg.jpg',
    backgroundImageAlt: 'A dining table set',
    parentId: 'parentId_of_Furniture',
    isActive: true,
  },
  {
    name: 'Cookware',
    slug: 'cookware',
    description: 'Pots and pans for all your cooking needs.',
    metadata: {
      item: 'cookware',
    },
    seoSlug: 'cookware-online',
    seoTitle: 'Pots, Pans & Skillets | Cookware',
    seoDescription:
      'Equip your kitchen with high-quality cookware. Find pots, pans, and skillets.',
    backgroundImage: 'https://example.com/images/cookware-bg.jpg',
    backgroundImageAlt: 'A stack of pans',
    parentId: 'parentId_of_Kitchenware',
    isActive: true,
  },
  {
    name: 'Bakeware',
    slug: 'bakeware',
    description: 'Baking sheets, pans, and molds.',
    metadata: {
      item: 'bakeware',
    },
    seoSlug: 'bakeware-supplies',
    seoTitle: 'Baking Sheets, Pans & Molds',
    seoDescription:
      'Bake delicious treats with our bakeware. Find baking sheets, pans, and molds.',
    backgroundImage: 'https://example.com/images/bakeware-bg.jpg',
    backgroundImageAlt: 'A baking sheet with cookies',
    parentId: 'parentId_of_Cooking_and_Baking',
    isActive: true,
  },
  {
    name: 'Cookbooks',
    slug: 'cookbooks',
    description: 'Cookbooks for all cuisines and skill levels.',
    metadata: {
      item: 'cookbook',
    },
    seoSlug: 'cookbooks-online',
    seoTitle: 'Cookbooks & Recipes | All Cuisines',
    seoDescription:
      'Learn to cook with our cookbooks. Find recipes from around the world.',
    backgroundImage: 'https://example.com/images/cookbook-bg.jpg',
    backgroundImageAlt: 'A person holding a cookbook',
    parentId: 'parentId_of_Cooking_and_Baking',
    isActive: true,
  },
  {
    name: 'Power Drills',
    slug: 'power-drills',
    description: 'Cordless and corded drills for any project.',
    metadata: {
      item: 'drill',
    },
    seoSlug: 'buy-power-drills',
    seoTitle: 'Cordless & Corded Drills | Shop Now',
    seoDescription:
      'Find the perfect drill for your projects. Cordless and corded options available.',
    backgroundImage: 'https://example.com/images/drill-bg.jpg',
    backgroundImageAlt: 'A power drill',
    parentId: 'parentId_of_Power_Tools',
    isActive: true,
  },
  {
    name: 'Screwdrivers',
    slug: 'screwdrivers',
    description: 'Screwdrivers for all your needs.',
    metadata: {
      item: 'screwdriver',
    },
    seoSlug: 'screwdrivers-set',
    seoTitle: 'Screwdriver Sets | Hand Tools',
    seoDescription:
      'Get a complete set of screwdrivers. Perfect for home and workshop use.',
    backgroundImage: 'https://example.com/images/screwdriver-bg.jpg',
    backgroundImageAlt: 'A person using a screwdriver',
    parentId: 'parentId_of_Hand_Tools',
    isActive: true,
  },
  {
    name: 'Drawing Pencils',
    slug: 'drawing-pencils',
    description: 'Pencils for sketching and drawing.',
    metadata: {
      item: 'pencil',
    },
    seoSlug: 'drawing-pencils-set',
    seoTitle: 'Pencils for Drawing | Art Supplies',
    seoDescription:
      'Find pencils for sketching, drawing, and shading. Perfect for artists of all levels.',
    backgroundImage: 'https://example.com/images/pencil-bg.jpg',
    backgroundImageAlt: 'A set of drawing pencils',
    parentId: 'parentId_of_Drawing',
    isActive: true,
  },
  {
    name: 'Sketchbooks',
    slug: 'sketchbooks',
    description: 'Sketchbooks for artists.',
    metadata: {
      item: 'sketchbook',
    },
    seoSlug: 'sketchbooks-online',
    seoTitle: 'Sketchbooks for Artists | Shop Now',
    seoDescription:
      'Find sketchbooks for all your drawing needs. Perfect for artists and designers.',
    backgroundImage: 'https://example.com/images/sketchbook-bg.jpg',
    backgroundImageAlt: 'A person drawing in a sketchbook',
    parentId: 'parentId_of_Drawing',
    isActive: true,
  },
  {
    name: 'Office Desks',
    slug: 'office-desks',
    description: 'Desks for your home or office.',
    metadata: {
      item: 'desk',
    },
    seoSlug: 'office-desks-for-sale',
    seoTitle: 'Desks for Home & Office | Shop Now',
    seoDescription:
      'Find the perfect desk for your workspace. From standing desks to corner desks.',
    backgroundImage: 'https://example.com/images/desk-bg.jpg',
    backgroundImageAlt: 'A modern office desk',
    parentId: 'parentId_of_Office_Furniture',
    isActive: true,
  },
  {
    name: 'Office Chairs',
    slug: 'office-chairs',
    description: 'Ergonomic chairs for comfortable seating.',
    metadata: {
      item: 'chair',
    },
    seoSlug: 'office-chairs-online',
    seoTitle: 'Ergonomic Office Chairs | Shop Now',
    seoDescription:
      'Sit comfortably with our ergonomic office chairs. Perfect for long work hours.',
    backgroundImage: 'https://example.com/images/chair-bg.jpg',
    backgroundImageAlt: 'An office chair',
    parentId: 'parentId_of_Office_Furniture',
    isActive: true,
  },
  {
    name: 'Gaming Laptops',
    slug: 'gaming-laptops',
    description: 'High-performance laptops for gaming.',
    metadata: {
      item: 'gaming-laptop',
    },
    seoSlug: 'gaming-laptops-for-sale',
    seoTitle: 'Gaming Laptops | High-Performance PCs',
    seoDescription:
      'Experience powerful gaming with our gaming laptops. Find laptops from top brands.',
    backgroundImage: 'https://example.com/images/gaming-laptop-bg.jpg',
    backgroundImageAlt: 'A gaming laptop',
    parentId: 'parentId_of_Laptops_and_Computers',
    isActive: true,
  },
  {
    name: 'Desktop PCs',
    slug: 'desktop-pcs',
    description: 'Desktops for home and office.',
    metadata: {
      item: 'desktop',
    },
    seoSlug: 'desktop-pcs-online',
    seoTitle: 'Desktop Computers | Home & Office PCs',
    seoDescription:
      'Find the perfect desktop for your needs. From compact to powerful gaming PCs.',
    backgroundImage: 'https://example.com/images/desktop-bg.jpg',
    backgroundImageAlt: 'A desktop computer',
    parentId: 'parentId_of_Laptops_and_Computers',
    isActive: true,
  },
  {
    name: 'Tablets',
    slug: 'tablets',
    description: 'Tablets for work and entertainment.',
    metadata: {
      item: 'tablet',
    },
    seoSlug: 'buy-tablets-online',
    seoTitle: 'Tablets | iPad, Samsung Galaxy Tab',
    seoDescription:
      'Browse our collection of tablets for work and fun. Find iPads, Samsung Galaxy Tab, and more.',
    backgroundImage: 'https://example.com/images/tablet-bg.jpg',
    backgroundImageAlt: 'A tablet on a desk',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'E-Readers',
    slug: 'e-readers',
    description: 'E-readers for reading on the go.',
    metadata: {
      item: 'e-reader',
    },
    seoSlug: 'e-readers-for-sale',
    seoTitle: 'E-Readers | Kindle & Kobo',
    seoDescription:
      'Read your favorite books on the go with our e-readers. Find Kindle and Kobo.',
    backgroundImage: 'https://example.com/images/ereader-bg.jpg',
    backgroundImageAlt: 'An e-reader in a hand',
    parentId: 'parentId_of_Electronics',
    isActive: true,
  },
  {
    name: 'Smartwatches',
    slug: 'smartwatches',
    description: 'Smartwatches to track your fitness and notifications.',
    metadata: {
      item: 'smartwatch',
    },
    seoSlug: 'buy-smartwatches-online',
    seoTitle: 'Smartwatches | Apple Watch, Samsung Galaxy Watch',
    seoDescription:
      'Stay connected and track your fitness with our smartwatches. Find Apple Watch, Samsung Galaxy Watch, and more.',
    backgroundImage: 'https://example.com/images/smartwatch-bg.jpg',
    backgroundImageAlt: 'A smartwatch on a wrist',
    parentId: 'parentId_of_Watches',
    isActive: true,
  },
  {
    name: 'Fitness Trackers',
    slug: 'fitness-trackers',
    description: 'Track your activity and health with our fitness trackers.',
    metadata: {
      item: 'tracker',
    },
    seoSlug: 'fitness-trackers-online',
    seoTitle: 'Fitness Trackers | Fitbit & Garmin',
    seoDescription:
      'Achieve your fitness goals with our trackers. Find Fitbit, Garmin, and more.',
    backgroundImage: 'https://example.com/images/tracker-bg.jpg',
    backgroundImageAlt: 'A person running with a fitness tracker',
    parentId: 'parentId_of_Watches',
    isActive: true,
  },
  {
    name: 'Crystals',
    slug: 'crystals',
    description: 'Crystals for healing and decoration.',
    metadata: {
      item: 'crystal',
    },
    seoSlug: 'buy-crystals-online',
    seoTitle: 'Healing Crystals | Shop Now',
    seoDescription:
      'Find crystals for meditation, healing, and decoration. From amethyst to quartz.',
    backgroundImage: 'https://example.com/images/crystal-bg.jpg',
    backgroundImageAlt: 'Various crystals on a table',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Candles',
    slug: 'candles',
    description: 'Scented candles for a relaxing atmosphere.',
    metadata: {
      item: 'candle',
    },
    seoSlug: 'scented-candles',
    seoTitle: 'Scented Candles | Soy & Beeswax',
    seoDescription:
      'Create a cozy atmosphere with our scented candles. Find soy and beeswax candles with various scents.',
    backgroundImage: 'https://example.com/images/candle-bg.jpg',
    backgroundImageAlt: 'A lit candle',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Wall Art',
    slug: 'wall-art',
    description: 'Paintings, prints, and posters for your walls.',
    metadata: {
      item: 'art',
    },
    seoSlug: 'wall-art-prints',
    seoTitle: 'Paintings & Prints for Walls',
    seoDescription:
      'Decorate your walls with our art prints. Find paintings, posters, and more.',
    backgroundImage: 'https://example.com/images/wall-art-bg.jpg',
    backgroundImageAlt: 'A painting on a wall',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Lamps',
    slug: 'lamps',
    description: 'Lamps for your home.',
    metadata: {
      item: 'lamp',
    },
    seoSlug: 'lamps-for-sale',
    seoTitle: 'Table Lamps, Floor Lamps & Chandeliers',
    seoDescription:
      'Light up your home with our lamps. Find table lamps, floor lamps, and chandeliers.',
    backgroundImage: 'https://example.com/images/lamp-bg.jpg',
    backgroundImageAlt: 'A modern lamp',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Bedding',
    slug: 'bedding',
    description: 'Sheets, pillows, and comforters for your bed.',
    metadata: {
      item: 'bedding',
    },
    seoSlug: 'bedding-sets-online',
    seoTitle: 'Bedding Sets, Sheets & Comforters',
    seoDescription:
      "Get a good night's sleep with our bedding. Find sheets, pillows, and comforters.",
    backgroundImage: 'https://example.com/images/bedding-bg.jpg',
    backgroundImageAlt: 'A neatly made bed',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Towels',
    slug: 'towels',
    description: 'Towels for your bathroom and kitchen.',
    metadata: {
      item: 'towel',
    },
    seoSlug: 'towels-online',
    seoTitle: 'Bath Towels & Kitchen Towels',
    seoDescription:
      'Find soft and absorbent towels for your bathroom and kitchen. All colors and sizes.',
    backgroundImage: 'https://example.com/images/towel-bg.jpg',
    backgroundImageAlt: 'A stack of folded towels',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Mugs',
    slug: 'mugs',
    description: 'Mugs for your coffee and tea.',
    metadata: {
      item: 'mug',
    },
    seoSlug: 'mugs-for-sale',
    seoTitle: 'Coffee Mugs & Tea Cups | Shop Now',
    seoDescription:
      'Enjoy your favorite beverage in our mugs. Find mugs for coffee, tea, and more.',
    backgroundImage: 'https://example.com/images/mug-bg.jpg',
    backgroundImageAlt: 'A coffee mug',
    parentId: 'parentId_of_Home_and_Garden',
    isActive: true,
  },
  {
    name: 'Plates',
    slug: 'plates',
    description: 'Plates for your dining table.',
    metadata: {
      item: 'plate',
    },
    seoSlug: 'plates-and-dishes',
    seoTitle: 'Dinner Plates & Bowls | Dinnerware',
    seoDescription:
      'Serve your meals with our plates and dishes. Find plates for every occasion.',
    backgroundImage: 'https://example.com/images/plate-bg.jpg',
    backgroundImageAlt: 'A stack of plates',
    parentId: 'parentId_of_Kitchenware',
    isActive: true,
  },
  {
    name: 'Gardening Supplies',
    slug: 'gardening-supplies',
    description: 'Supplies for your garden.',
    metadata: {
      item: 'supply',
    },
    seoSlug: 'gardening-supplies-online',
    seoTitle: 'Seeds, Soil & Planters | Gardening',
    seoDescription:
      'Find everything for your garden. Seeds, soil, planters, and more.',
    backgroundImage: 'https://example.com/images/seed-bg.jpg',
    backgroundImageAlt: 'A person planting a seed',
    parentId: 'parentId_of_Garden_Tools',
    isActive: true,
  },
  {
    name: 'Outdoor Furniture',
    slug: 'outdoor-furniture',
    description: 'Furniture for your patio and garden.',
    metadata: {
      item: 'outdoor-furniture',
    },
    seoSlug: 'outdoor-furniture-for-sale',
    seoTitle: 'Patio Furniture & Garden Chairs',
    seoDescription:
      'Furnish your outdoor space with our furniture. Find chairs, tables, and sofas for your patio.',
    backgroundImage: 'https://example.com/images/patio-bg.jpg',
    backgroundImageAlt: 'A patio with chairs',
    parentId: 'parentId_of_Furniture',
    isActive: true,
  },
  {
    name: 'Sports Apparel',
    slug: 'sports-apparel',
    description: 'Apparel for all sports.',
    metadata: {
      type: 'apparel',
    },
    seoSlug: 'sports-apparel-online',
    seoTitle: 'Workout Clothes & Sportswear',
    seoDescription:
      'Find comfortable and stylish apparel for all your sports needs. From running to yoga.',
    backgroundImage: 'https://example.com/images/sports-apparel-bg.jpg',
    backgroundImageAlt: 'A person in workout clothes',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Water Bottles',
    slug: 'water-bottles',
    description: 'Reusable water bottles for your daily hydration.',
    metadata: {
      item: 'bottle',
    },
    seoSlug: 'reusable-water-bottles',
    seoTitle: 'Water Bottles | Stainless Steel & Plastic',
    seoDescription:
      'Stay hydrated on the go with our reusable water bottles. Find stainless steel and plastic options.',
    backgroundImage: 'https://example.com/images/bottle-bg.jpg',
    backgroundImageAlt: 'A water bottle on a table',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Car Maintenance',
    slug: 'car-maintenance',
    description: 'Products for car maintenance.',
    metadata: {
      type: 'maintenance',
    },
    seoSlug: 'car-maintenance-products',
    seoTitle: 'Engine Oil, Wipers & Filters',
    seoDescription:
      'Keep your car in top condition with our maintenance products. Engine oil, wipers, and more.',
    backgroundImage: 'https://example.com/images/oil-bg.jpg',
    backgroundImageAlt: 'A bottle of engine oil',
    parentId: 'parentId_of_Automotive',
    isActive: true,
  },
  {
    name: 'Car Cleaning',
    slug: 'car-cleaning',
    description: 'Products for cleaning your car.',
    metadata: {
      type: 'cleaning',
    },
    seoSlug: 'car-cleaning-supplies',
    seoTitle: 'Car Wash, Wax & Polish',
    seoDescription:
      'Keep your car sparkling clean with our cleaning supplies. Car wash, wax, and polish.',
    backgroundImage: 'https://example.com/images/car-wash-bg.jpg',
    backgroundImageAlt: 'A person washing a car',
    parentId: 'parentId_of_Automotive',
    isActive: true,
  },
  {
    name: 'Car Electronics',
    slug: 'car-electronics',
    description: 'Electronics for your car.',
    metadata: {
      type: 'electronics',
    },
    seoSlug: 'car-electronics-store',
    seoTitle: 'Car Stereos, Speakers & GPS',
    seoDescription:
      "Upgrade your car's sound system with our electronics. Stereos, speakers, and GPS.",
    backgroundImage: 'https://example.com/images/car-stereo-bg.jpg',
    backgroundImageAlt: 'A car stereo',
    parentId: 'parentId_of_Automotive',
    isActive: true,
  },
  {
    name: 'Tires',
    slug: 'tires',
    description: 'Tires for all vehicles.',
    metadata: {
      type: 'tire',
    },
    seoSlug: 'buy-tires-online',
    seoTitle: 'Car & Truck Tires | All-Season & Winter',
    seoDescription:
      'Find the perfect tires for your vehicle. All-season, winter, and performance tires.',
    backgroundImage: 'https://example.com/images/tire-bg.jpg',
    backgroundImageAlt: 'A stack of tires',
    parentId: 'parentId_of_Automotive',
    isActive: true,
  },
  {
    name: 'Car Seats',
    slug: 'car-seats',
    description: 'Car seats for babies and toddlers.',
    metadata: {
      type: 'car-seat',
    },
    seoSlug: 'car-seats-for-babies',
    seoTitle: 'Baby & Toddler Car Seats',
    seoDescription:
      'Keep your child safe with our car seats. Find infant car seats and boosters.',
    backgroundImage: 'https://example.com/images/car-seat-bg.jpg',
    backgroundImageAlt: 'A baby car seat',
    parentId: 'parentId_of_Automotive',
    isActive: true,
  },
  {
    name: 'Motorcycles',
    slug: 'motorcycles',
    description: 'Motorcycle parts and accessories.',
    metadata: {
      type: 'motorcycle',
    },
    seoSlug: 'motorcycle-parts-accessories',
    seoTitle: 'Motorcycle Helmets, Jackets & Parts',
    seoDescription:
      'Find everything for your motorcycle. Helmets, jackets, and engine parts.',
    backgroundImage: 'https://example.com/images/motorcycle-bg.jpg',
    backgroundImageAlt: 'A motorcycle',
    parentId: 'parentId_of_Automotive',
    isActive: true,
  },
  {
    name: 'Boating',
    slug: 'boating',
    description: 'Boating supplies and equipment.',
    metadata: {
      activity: 'boating',
    },
    seoSlug: 'boating-supplies',
    seoTitle: 'Boating Gear & Life Vests',
    seoDescription:
      'Get ready for the water with our boating supplies. Life vests, ropes, and more.',
    backgroundImage: 'https://example.com/images/boat-bg.jpg',
    backgroundImageAlt: 'A boat on a lake',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Fishing',
    slug: 'fishing',
    description: 'Fishing rods, reels, and bait.',
    metadata: {
      activity: 'fishing',
    },
    seoSlug: 'fishing-gear-supplies',
    seoTitle: 'Fishing Rods, Reels & Bait',
    seoDescription:
      'Catch your next big fish with our fishing gear. Rods, reels, and bait for all types of fishing.',
    backgroundImage: 'https://example.com/images/fishing-bg.jpg',
    backgroundImageAlt: 'A person fishing',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Golf',
    slug: 'golf',
    description: 'Golf clubs, balls, and apparel.',
    metadata: {
      activity: 'golf',
    },
    seoSlug: 'golf-clubs-and-balls',
    seoTitle: 'Golf Clubs, Balls & Apparel',
    seoDescription:
      'Improve your game with our golf gear. Clubs, balls, and apparel for all golfers.',
    backgroundImage: 'https://example.com/images/golf-bg.jpg',
    backgroundImageAlt: 'A person playing golf',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Team Sports',
    slug: 'team-sports',
    description:
      'Equipment for team sports like basketball, football, and soccer.',
    metadata: {
      activity: 'team-sport',
    },
    seoSlug: 'team-sports-equipment',
    seoTitle: 'Basketball, Soccer & Football Gear',
    seoDescription:
      'Find equipment for your favorite team sports. Balls, jerseys, and more.',
    backgroundImage: 'https://example.com/images/team-sports-bg.jpg',
    backgroundImageAlt: 'A basketball on a court',
    parentId: 'parentId_of_Sports_and_Outdoors',
    isActive: true,
  },
  {
    name: 'Fitness Machines',
    slug: 'fitness-machines',
    description: 'Treadmills, ellipticals, and weights.',
    metadata: {
      item: 'machine',
    },
    seoSlug: 'treadmills-ellipticals-weights',
    seoTitle: 'Treadmills, Ellipticals & Home Gyms',
    seoDescription:
      'Build your home gym with our fitness machines. Treadmills, ellipticals, and weights for a full-body workout.',
    backgroundImage: 'https://example.com/images/treadmill-bg.jpg',
    backgroundImageAlt: 'A treadmill in a gym',
    parentId: 'parentId_of_Fitness',
    isActive: true,
  },
  {
    name: 'Fitness Apparel',
    slug: 'fitness-apparel',
    description: 'Workout clothes for men and women.',
    metadata: {
      item: 'apparel',
    },
    seoSlug: 'workout-clothes-online',
    seoTitle: 'Workout Clothes & Activewear',
    seoDescription:
      'Find comfortable and stylish workout clothes. Perfect for the gym or a run.',
    backgroundImage: 'https://example.com/images/activewear-bg.jpg',
    backgroundImageAlt: 'A person in activewear',
    parentId: 'parentId_of_Fitness',
    isActive: true,
  },
  {
    name: 'Protein Powders',
    slug: 'protein-powders',
    description: 'Whey, casein, and plant-based protein powders.',
    metadata: {
      type: 'protein',
    },
    seoSlug: 'protein-powder-supplements',
    seoTitle: 'Whey & Plant-Based Protein Powder',
    seoDescription:
      'Build muscle and recover with our protein powders. Find whey, casein, and plant-based options.',
    backgroundImage: 'https://example.com/images/protein-bg.jpg',
    backgroundImageAlt: 'A scoop of protein powder',
    parentId: 'parentId_of_Supplements',
    isActive: true,
  },
  {
    name: 'Vitamins',
    slug: 'vitamins',
    description: 'Vitamins and minerals for your health.',
    metadata: {
      type: 'vitamin',
    },
    seoSlug: 'vitamins-and-minerals',
    seoTitle: 'Vitamins & Supplements | Shop Now',
    seoDescription:
      'Boost your health with our vitamins and minerals. Find multivitamins, Vitamin C, and more.',
    backgroundImage: 'https://example.com/images/vitamin-bg.jpg',
    backgroundImageAlt: 'A bottle of vitamins',
    parentId: 'parentId_of_Supplements',
    isActive: true,
  },
  {
    name: 'Bodybuilding',
    slug: 'bodybuilding',
    description: 'Supplements and equipment for bodybuilding.',
    metadata: {
      activity: 'bodybuilding',
    },
    seoSlug: 'bodybuilding-supplements',
    seoTitle: 'Bodybuilding Supplements & Gear',
    seoDescription:
      'Find everything you need for bodybuilding. Protein, creatine, and workout gear.',
    backgroundImage: 'https://example.com/images/bodybuilding-bg.jpg',
    backgroundImageAlt: 'A person lifting weights',
    parentId: 'parentId_of_Fitness',
    isActive: true,
  },
  {
    name: 'Yoga',
    slug: 'yoga',
    description: 'Yoga mats, clothes, and accessories.',
    metadata: {
      activity: 'yoga',
    },
    seoSlug: 'yoga-mats-and-clothes',
    seoTitle: 'Yoga Mats, Clothes & Accessories',
    seoDescription:
      'Enhance your practice with our yoga gear. Mats, clothes, and accessories for all levels.',
    backgroundImage: 'https://example.com/images/yoga-bg.jpg',
    backgroundImageAlt: 'A person doing a yoga pose',
    parentId: 'parentId_of_Fitness',
    isActive: true,
  },
  {
    name: 'Camping Tents',
    slug: 'camping-tents',
    description: 'Tents for all sizes and weather conditions.',
    metadata: {
      item: 'tent',
    },
    seoSlug: 'camping-tents-for-sale',
    seoTitle: 'Camping Tents | 2-Person & Family',
    seoDescription:
      'Find the perfect tent for your camping trip. From 2-person to large family tents.',
    backgroundImage: 'https://example.com/images/tent-bg.jpg',
    backgroundImageAlt: 'A tent in a campsite',
    parentId: 'parentId_of_Camping_and_Hiking',
    isActive: true,
  },
  {
    name: 'Backpacks',
    slug: 'backpacks',
    description: 'Backpacks for hiking and everyday use.',
    metadata: {
      item: 'backpack',
    },
    seoSlug: 'hiking-backpacks',
    seoTitle: 'Hiking Backpacks & Daypacks',
    seoDescription:
      'Carry your gear with our hiking backpacks. Find backpacks for all your outdoor needs.',
    backgroundImage: 'https://example.com/images/backpack-bg.jpg',
    backgroundImageAlt: 'A backpack on a trail',
    parentId: 'parentId_of_Camping_and_Hiking',
    isActive: true,
  },
  {
    name: 'Sleeping Bags',
    slug: 'sleeping-bags',
    description: 'Sleeping bags for all seasons.',
    metadata: {
      item: 'sleeping-bag',
    },
    seoSlug: 'sleeping-bags-online',
    seoTitle: 'Sleeping Bags | Summer & Winter',
    seoDescription:
      'Stay warm and comfortable with our sleeping bags. Find bags for all seasons.',
    backgroundImage: 'https://example.com/images/sleeping-bag-bg.jpg',
    backgroundImageAlt: 'A person in a sleeping bag',
    parentId: 'parentId_of_Camping_and_Hiking',
    isActive: true,
  },
];
