export enum CategoryCodeEnum {
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_ALREADY_EXISTS = 'CATEGORY_NAME_ALREADY_EXISTS',
  CATEGORY_SLUG_ALREADY_EXISTS = 'CATEGORY_SLUG_ALREADY_EXISTS',
}
