export enum CollectionCodeEnum {
  COLLECTION_NOT_FOUND = 'COLLECTION_NOT_FOUND',
  COLLECTION_NAME_ALREADY_EXISTS = 'COLLECTION_NAME_ALREADY_EXISTS',
  COLLECTION_SLUG_ALREADY_EXISTS = 'COLLECTION_SLUG_ALREADY_EXISTS',
}
