// src/enums/code-enum.ts
export enum CodeEnum {
  DISCOUNT_ALREADY_EXISTS = 'DISCOUNT_ALREADY_EXISTS',
  DISCOUNT_NOT_FOUND = 'DISCOUNT_NOT_FOUND',
  DISCOUNT_CREATE_FAILED = 'DISCOUNT_CREATE_FAILED',
  DISCOUNT_UPDATE_FAILED = 'DISCOUNT_UPDATE_FAILED',
  DISCOUNT_DELETE_FAILED = 'DISCOUNT_DELETE_FAILED',
}
