export enum ProductCodeEnum {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_NAME_ALREADY_EXISTS = 'PRODUCT_NAME_ALREADY_EXISTS',
  PRODUCT_SLUG_ALREADY_EXISTS = 'PRODUCT_SLUG_ALREADY_EXISTS',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
}
